name: build

on:
  # run on push to repo
  push:
    branches: [ "main" ]

  # run on manual dispatch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Get repo content
      - uses: actions/checkout@v3

      # Make image
      - run: sudo bash create_image.sh

      # Upload image as artifact
      - uses: actions/upload-artifact@v3
        with:
          name: image
          path: ${{ github.workspace }}/jetson_image.img