# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # # Gives more space for actions
      # - uses: easimon/maximize-build-space@master
      #   with:
      #     root-reserve-mb: 32768
      #     remove-dotnet: true
      #     remove-android: true
      #     remove-haskell: true

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Make rootfs
      - run: sudo bash image.sh

      # Upload output
      - uses: actions/upload-artifact@v3
        with:
          name: image
          path: /home/runner/work/jetson/jetson/JETSON.img
