name: release

on:
  # Run on manual dispatch
  workflow_dispatch:
    inputs:
        tag:
          required: true
          type: string


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Get repo content
      - uses: actions/checkout@v3

      # Make image
      - run: sudo bash create_image.sh

      # compress image
      - run: sudo xz -T0 -9 ${{ github.workspace }}/jetson_image.img

      # Upload output
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ github.workspace }}/jetson_image.img.xz
          tag: ${{ inputs.tag }}