name: release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Make rootfs
      - run: sudo bash create_image.sh

      # Upload output
      - uses: ncipollo/release-action@v1
        with:
          artifacts: ${{github.workspace}}/jetson_image.img
          tag: v0.1